/*
 ==============================================================================
 
 This file was auto-generated by the Introjucer!
 
 It contains the basic framework code for a JUCE plugin editor.
 
 ==============================================================================
 */

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
 */
class MiditoOscAudioProcessorEditor  : public AudioProcessorEditor,
public SliderListener,
public ComboBoxListener,
public ButtonListener,
public TextEditorListener,
private Timer
{
public:
    MiditoOscAudioProcessorEditor (MiditoOscAudioProcessor&);
    ~MiditoOscAudioProcessorEditor();
    
    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    
    void sliderValueChanged (Slider* sliderThatWasMoved) override;
    void comboBoxChanged (ComboBox* comboBoxThatHasChanged) override;
    void buttonClicked (Button* buttonThatWasClicked) override;
    void textEditorReturnKeyPressed (TextEditor& textEditorChanged) override;
    
    void timerCallback() override;
    
    //==============================================================================
    
    
private:
    
    enum parameters
    {
        Polyphony = 0,
        Glide = 1,
        Mono = 2,
        Shift = 3,
        Scale = 4,
        
        Linear = 0,
        Chromatic = 1,
        Major = 2,
        M7 = 3,
        Min7 = 4,
        Dorian = 5,
        Minor = 6,
        fifth = 7,
        Whole = 8,
        Calib = 9
    };
    
    bool reconnect = false;
    
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    MiditoOscAudioProcessor& processor;
    
    //==============================================================================
    ScopedPointer<TextEditor> remoteAddressText;
    ScopedPointer<TextEditor> remotePortText;
    ScopedPointer<Slider> maxPoly;
    ScopedPointer<Slider> glide;
    ScopedPointer<Label> labelPolyphony;
    ScopedPointer<Label> labelGlide;
    ScopedPointer<ComboBox> scaleSelect;
    ScopedPointer<Label> labelScale;
    ScopedPointer<TextButton> shiftButton;
    ScopedPointer<Label> labelMOSC;
    ScopedPointer<TextButton> monoButton;
    ScopedPointer<TextButton> loadCalibButton;
    Path internalPath1;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MiditoOscAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
